// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwQ3Fd2jf6-fcH1RAFs5_Cyu2QWaG6BXk',
    appId: '1:30115558843:web:d67753cecf2c773ae0409e',
    messagingSenderId: '30115558843',
    projectId: 'smart-queue-6aaf4',
    authDomain: 'smart-queue-6aaf4.firebaseapp.com',
    storageBucket: 'smart-queue-6aaf4.firebasestorage.app',
    measurementId: 'G-DTJLFXJECQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWTDkmEuNFOcatwKyIprxA7uq-Y29nBUM',
    appId: '1:30115558843:android:c3ee88119fb9f707e0409e',
    messagingSenderId: '30115558843',
    projectId: 'smart-queue-6aaf4',
    storageBucket: 'smart-queue-6aaf4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTJ16ac6hA4i7lg9ovE9FLPihSp49IKrU',
    appId: '1:30115558843:ios:799ec8f3b719e73ce0409e',
    messagingSenderId: '30115558843',
    projectId: 'smart-queue-6aaf4',
    storageBucket: 'smart-queue-6aaf4.firebasestorage.app',
    iosBundleId: 'com.example.smartQueue',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTJ16ac6hA4i7lg9ovE9FLPihSp49IKrU',
    appId: '1:30115558843:ios:799ec8f3b719e73ce0409e',
    messagingSenderId: '30115558843',
    projectId: 'smart-queue-6aaf4',
    storageBucket: 'smart-queue-6aaf4.firebasestorage.app',
    iosBundleId: 'com.example.smartQueue',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwQ3Fd2jf6-fcH1RAFs5_Cyu2QWaG6BXk',
    appId: '1:30115558843:web:d0f14d055cb7e0fbe0409e',
    messagingSenderId: '30115558843',
    projectId: 'smart-queue-6aaf4',
    authDomain: 'smart-queue-6aaf4.firebaseapp.com',
    storageBucket: 'smart-queue-6aaf4.firebasestorage.app',
    measurementId: 'G-M3NWC1C60E',
  );
}
