name: Build Flutter iOS IPA (Unsigned Export)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Flutter 3.32.2
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.2'

      - name: Verify Flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      # 🔹 Build archive & IPA (no signing)
      - name: Build iOS IPA (no codesign)
        run: flutter build ipa --release --no-codesign

      # 🔹 Generate ExportOptions.plist dynamically
      - name: Generate ExportOptions.plist
        run: |
          mkdir -p ios
          cat <<EOF > ios/ExportOptions.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>ad-hoc</string>
            <key>signingStyle</key>
            <string>manual</string>
            <key>compileBitcode</key>
            <false/>
            <key>destination</key>
            <string>export</string>
            <key>stripSwiftSymbols</key>
            <true/>
            <key>thinning</key>
            <string>&lt;none&gt;</string>
          </dict>
          </plist>
          EOF

      # 🔹 Create IPA directory
      - name: Create IPA directory
        run: mkdir -p build/ios/ipa

      # 🔹 Export IPA from the generated archive
      - name: Export unsigned IPA manually
        run: |
          if [ -d "build/ios/archive/Runner.xcarchive" ]; then
            echo "Found archive, exporting..."
            xcodebuild -exportArchive \
              -archivePath build/ios/archive/Runner.xcarchive \
              -exportPath build/ios/ipa \
              -exportOptionsPlist ios/ExportOptions.plist || true
          else
            echo "⚠️ Archive not found, using Flutter output IPA instead (if exists)"
          fi

      # 🔹 Upload IPA artifact
      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Runner-IPA
          path: build/ios/ipa/
